apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-prod
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: project/argocd/manifests
    repoURL: https://github.com/hungdq1379/Udacity_CloudNativeArchitecture_2
    targetRevision: HEAD

