## provide the name of the namespace
namespace name: staging
service:
  port: 5111

## define the image to execute with the Deployment 
image:
  repository: techtrends 
  tag: latest
  pullPolicy: Always

## set the number of replicas for an application 
replicaCount: 5
resources:
  requests:
    cpu: 90Mi
    memory: 300m
  limits:
    cpu: 256Mi
    memory: 500m
