## provide the name of the namespace
namespace name: prod
service:
  port: 7111

## define the image to execute with the Deployment 
image:
  repository: techtrends 
  tag: latest
  pullPolicy: Always

## set the number of replicas for an application 
replicaCount: 5
resources:
  requests:
    cpu: 128M
    memory: 350m
  limits:
    cpu: 256Mi
    memory: 500m
