## provide the name of the namespace
namespace name: staging
service port: 5111

## define the image to execute with the Deployment 
image:
  repository: techtrends 
  tag: latest
  pullPolicy: Always

## set the number of replicas for an application 
replicaCount: 5
resources:
  requests: memory 90Mi and CPU 300m
  limits: memory 256Mi and CPU 500m
