## provide the name of the namespace
namespace:
  name: prod
service:
  port: 7111

## define the image to execute with the Deployment 
image:
  repository: hungdq1379/techtrends
  tag: latest
  pullPolicy: Always

## set the number of replicas for an application 
replicaCount: 5
resources:
  requests:
    cpu: 350m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
