## provide the name of the namespace
namespace:
  name: sandbox
service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP
## define the image to execute with the Deployment 
image:
  repository: techtrends 
  tag: latest
  pullPolicy: IfNotPresent

## set the number of replicas for an application 
replicaCount: 1
resources:
  requests:
    cpu: 64Mi
    memory: 250m
  limits:
    cpu: 128Mi
    memory: 500m
containerPort: 3111
livenessProbe path: /healthz
readinessProbe path: /healthz
